USE DB_MAGAZZINO;

SET FOREIGN_KEY_CHECKS=0;

CREATE or REPLACE DATABASE DB_MAGAZZINO;

USE DB_MAGAZZINO;

CREATE TABLE tecnico (
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  cognome varchar(255),
  nome varchar(255),
  targa varchar(255)
);

CREATE TABLE prodotto (
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  codice varchar(255),
  descrizione varchar(255),
  quantita int(255),
  stato varchar(255)
);

CREATE TABLE tracciamento (
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  id_prodotto int(255),
  id_tecnico int(255),
  quantita int(255),
  stato varchar(10),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tracciamento ADD INDEX index_prodotto (id_prodotto);
ALTER TABLE tracciamento ADD INDEX index_tecnico (id_tecnico);

ALTER TABLE tracciamento ADD CONSTRAINT fk_prodotto_id FOREIGN KEY (id_prodotto) REFERENCES prodotto(id);
ALTER TABLE tracciamento ADD CONSTRAINT fk_tecnico_id FOREIGN KEY (id_tecnico) REFERENCES tecnico(id);



INSERT INTO tecnico (id, cognome, nome, targa) VALUES (1, 'potereanu', 'andrian', 'AG12345');
INSERT INTO tecnico (id, cognome, nome, targa) VALUES (2, 'derosa', 'federico', 'FR12345');
INSERT INTO tecnico (id, cognome, nome, targa) VALUES (3, 'tarantino', 'giorgio', 'TY12345');


INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	1	,	'CAB-PROL-CASH BASIC',	'PROLUNGA CASSETTO CASH BASIC',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	2	,	'CAB-PROL-D5-PORTA 3',	'PROLUNGA CASSETTO D5',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	3	,	'CAB-PROL-D5-PLUG',	'PROLUNGA D5 PLUG',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	4	,	'CAB-CASSETTO ANKER',	'CAVO PER CASSETTO ANKER H&M',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	5	,	'CAB-CASSETTO-4610',	'CAVO PER CASSETTO IBM ATTACCO 4610',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	6	,	'CAB-SERIALE NURIT',	'CAVO SERIALE PER PIN PAD NURIT',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	7	,	'CAB-USB-GENERICO',	'CAVO PER STAMPANTE USB GENERICO',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	8	,	'CAB-TAST-H&M',	'CAVO PER TASTIERA H&M',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	9	,	'CAB-9/25',	'CAVO SERIALE 9 PIN-25 PIN',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	10	,	'8-03734-10',	'CAVO USB PER SCANNER QS6XXX,MGL 1XXX',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	11	,	'8-0731-08',	'CAVO AUTOALIMENTATO PER HS2300/HS2200',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	12	,	'8-0731-02',	'CAVO PER SCANNER 381/383/8XXX/HS2X00 CON POWER',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	13	,	'8-0736-80',	'CAVO QS6XXX/MGL 1X00 RS232 NON ALIMENTATO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	14	,	'8-0739-04',	'CAVO PER QS6XXX/MGL1X00 PORTA 9',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	15	,	'8-0863-02',	'CAVO USB PER SCANNER 8300',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	16	,	'8-0938-02',	'CAVO USB PER SCANNER ?',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	17	,	'CAB-USB-QS6XXX',	'CAVO PER QS6XXX/MGL1X00 USB',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	18	,	'CAB-RS232-DX530',	'CAVO SERIALE PER SCANNER D8530/9530',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	19	,	'90G001010',	'CAVO KWB PER SCANNER DATALOGIC D130,HERON',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	20	,	'90A051945',	'CAVO USB PER SCANNER DATALOGIC D130,HERON',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	21	,	'CAB-DENSO',	'CAVO SERIALE PER SCANNER DENSO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	22	,	'CAB-RS232-MS9590',	'CAVO RS232 PER SCANNER MS9590 ',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	23	,	'CAB-9E-MS9590',	'CAVO PORTA 9E PER SCANNER MS9590',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	24	,	'CAB-USB-MS9590',	'CAVO USB PER SCANNER',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	25	,	'CAB-9E-LS2208/C6R',	'CAVO PORTA 9E PER SCANNER LS220 E BANCOLINI C6R',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	26	,	'CAB-USB-LS2208/CSR',	'CAVO USB PER SCANNER LS220 E BANCOLINI C6R',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	27	,	'CAB-9E-QD2X00',	'CAVO PORTA 9 PER QD2X00',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	28	,	'CAB-USB-QD2X00',	'CAVO USB PER SCANNER DATALOGIC QD2X00',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	29	,	'CAB-USB-QD2131',	'CAVO USB PER SCANNER DATALOGIC QD2131',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	30	,	'CAB-USB-9800',	'CAVO USB PER SCANNER DA BANCO 9800',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	31	,	'CAB-USB-8300',	'CAVO USB PER SCANNER 8300',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	32	,	'CAB-USB-HS3300',	'CAVO USB PER HS3300',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	33	,	'CAB-USB-1450',	'CAVO USB PER SCANNER HONEYWEEL 1450',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	34	,	'CAB-TOUCH-LCD3000',	'CAVO TOUCH PER MONITOR FUJITSU LCD3000',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	35	,	'CAB-VGA-GEN',	'CAVO VGA GENERICO',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	36	,	'CAB-VGA-46D',	'CAVO VGA PER MONITOR 46D',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	37	,	'CAB-MSR/TOUCH/PS2-2WB',	'CAVO PER MONITOR 2WB MSR/TOUCH/PS2',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	38	,	'CAB-USB-51W/5LG',	'CAVO USB AUTOALIM.PER MONITOR 51W/5LG',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	39	,	'CAB-USB-5WB',	'CAVO TOUCH PER MONITOR 5WB',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	40	,	'CAB-3',	'CAVO 3 CASSETTO IBM',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	41	,	'CAB-4',	'CAVO 4 VISORE IBM',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	42	,	'CAB-4-A&S',	'CAVI 4 PER ROLL OUT A&S',	5,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	43	,	'CAB-5',	'CAVO 5 TASTIERA IBM',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	44	,	'CAB-7',	'CAVO 7 STAMPANTE IBM',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	45	,	'CAB-Y',	'CAVO Y SDOPPIATORE CAVO 4 IBM',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	46	,	'CAB-ALIM-2P',	'CAVO D ALIMENTAZIONE 2 POLI',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	47	,	'CAB-ALIM-3P',	'CAVO D ALIMENTAZIONE 3 POLI',	9,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	48	,	'CAB-ALIM-4820',	'CAVO D ALIMENTAZIONE PER POWER 4820',	10,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	49	,	'CAB-RETE',	'CAVI DI RETE',	7,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	50	,	'CAB-SERIALE-II250',	'CAVO SERIALE PER PIN PAD INGENICO II250',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	51	,	'CAB-USB-II250',	'CAVO USB PER PIN PAD INGENICO II250',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	52	,	'CAB-USB-TM88',	'CAVO USB AUTOALMENTATO PER STAMP.EPSON TM88',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	53	,	'CAB-USB-1NF',	'CAVO USB AUTOALIMENTATO PER STAMP.TOSCHIBA 4610-1NF',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	54	,	'CAB-USB-USB-NCR',	'CAVO USN AUTOALINENTATO PER STAMPANTE NCR DUAL SIDE',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	55	,	'CAB-RS232-KD3/5',	'CAVO SERIALE STAMPANTE 4610-KD3/5',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	56	,	'CAB-RS232-EPSON',	'CAVO SERIALE PER STAMPANTE EPSON MODELLO FP',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	57	,	'CAB-RS232-KUBE/PD',	'CAVO SERIALE PER STAMPANTE KUBE/PD',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	58	,	'CAB-SR23S/PLUG',	'CAVO SERIALE -USB PER CONFIGURAZIONE SWITCH',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	59	,	'SUPPORTO-VIS-5503',	'SUPPORTO IN PLASTICA VISORE IBM 5503',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	60	,	'SUPPORTO-VIS-5501',	'SUPPORTO IN PLASTICA VISOTE IBM 5501',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	61	,	'CARD-SERIALI-722',	'SCHEDE SERIALI AGGIUNTIVE 4800-722',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	62	,	'RISER-CARD-722',	'SCHEDA RISERDCARD PER SURE POS 4800-722',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	63	,	'SK-485-46101NR',	'INTERFACCIA IBM RS485 (CAVO 7) PER 4610 1NR',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	64	,	'SK-USB-46101NR',	'INTERFACCIA IBM USB  PER 4610 1NR',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	65	,	'EPROM 5C',	'EPROM 5C',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	66	,	'RAM-721-256MB',	'SCHEDA DI MEMORIA DA 256MB PER SURE POS 4800-721',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	67	,	'RAM-722-516MB',	'SCHEDA DI MEMORIA DA 516MB PER SURE POS 4800-722',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	68	,	'RAM-722-1GB',	'SCHEDA DI MEMORIA DA 1 GB PER SURE POS 4800-722',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	69	,	'RAM-723-256MB',	'SCHEDA DI MEMORIA DA 256 MB PER SURE POS 4800-723',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	70	,	'RAM-723-1 GB',	'SCHEDA DI MEMORIA DA 1 GB PER SURE POS 4800-723',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	71	,	'POWER-EPSON',	'ALIMENTATORE PER STAMPANTI FISC. EPSON FP',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	72	,	'POWER-KUBE/PD',	'ALIMENTATORE CUSTOM PER STAMPANTI FISC KUBE/PD215',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	73	,	'POWER-KIOSK-IBM',	'ALIMENTATORE PER KIOSK IBM 4838-XXX',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	74	,	'POWER-KIOSK-NCR',	'ALIMENTATORE PER KIOSK NCR ESSELUNGA',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	75	,	'POWER-MQ212/215',	'ALIMENTATORE PER MONITOR MULTIQ MOD. MQ212/215',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	76	,	'POWER-8X00',	'ALIMENTATORE PER SCANNER DA BANCO 8200/8100',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	77	,	'POWER-8300',	'ALIMENTATORE PER SCANNER DATALOGIC 8300',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	78	,	'POWER-9800',	'ALIMENTATORE PER SCANNER DA BANCO DATALOGIC 9800',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	79	,	'POWER-II250',	'ALIMENTATORE PER PIN PAD INGENICO II250',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	80	,	'POWER-II320',	'ALIMENTATORE PER PIN PAD INGENICO II320',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	81	,	'POWER-4820',	'ALIMENTATORE PER MONITOR IBM 4820',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	82	,	'POWER-4610KDX',	'ALIMENTATORE PER STAMPANTE FISCALE 4610-KDX',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	83	,	'POWER-722',	'ALIMENTATORE BASE CASSA SURE POS 4800-722',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	84	,	'POWER-723',	'ALIMENTATORE BASE CASSA SURE POS4800-723',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	85	,	'POWER-VS800',	'ALIMENTATORE PER SCANNER VS800/HS2300/HS2200',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	86	,	'POWER-DX539-12V',	'ALIMENTATORE PER SCANNER DATALOGIC D8530/D9530 12V',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	87	,	'POWER-DX539-5V',	'ALIMENTATORE PER SCANNER DATALOGIC D8530/D9530 5V',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	88	,	'BD750',	'GRUPPO DI CONTINUITA 750A',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	89	,	'6140-120',	'BASE CASSA TW TOSHIBA',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	90	,	'4800-722',	'BASE CASSA SURE POS 4800-722',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	91	,	'4800-723',	'BASE CASSE SURE POS 4800-723',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	92	,	'4800-743',	'BASE CASSA SURE POS 4800-743',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	93	,	'4810-32H',	'BASE CASSA SURE POS 4810-32H',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	94	,	'4810-33H',	'BASE CASSA SURE POS 4810-33H',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	95	,	'4900-745',	'BASE CASSA SURE POS 4900-745',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	96	,	'TPX',	'BASE CASSA PC FUJITSU MOD.TPX ',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	97	,	'TPXII',	'BASE CASSA PC FUJITSU MOD.TPX II',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	98	,	'C5900',	'BASE CASSA PC FUJITSU MOD.C5900',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	99	,	'8212-CTO',	'PC LENOVO MODELLO 8212-CTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	100	,	'2582-AC1',	'PC SERVER X3400 TOYS',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	101	,	'QS6500-USB',	'PISTOLA SCANNER QS6500 IF USB',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	102	,	'QS6500-RS232',	'PISTOLA SCANNER QS6500 IF RS232',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	103	,	'QS6500-KWB',	'PISTOLA SCANNER QS6500 IF KWB',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	104	,	'LS2208',	'PISTOLA SCANNER SYMBOL LS2208',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	105	,	'C6R',	'PISTOLA SCANNER BANCOLINI CSR',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	106	,	'MGL1100-A&S',	'PISTOLA SCANNER MAGELLAN 1100 A&S',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	107	,	'MGL1000',	'PISTOLA SCANNER MAGELLAN 1000',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	108	,	'MS9590-USB',	'PISTOLA SCANNER METROLOGIC MS9590 IF USB',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	109	,	'MS9590-RS232',	'PISTOLA SCANNER METROLOGIC MS9590 IF RS232',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	110	,	'DENSO',	'PISTOLA SCANNER FUJITSU DENSO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	111	,	'D100',	'PISTOLA SCANNER DATALOGIC GRIFFON D100',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	112	,	'D130',	'PISTOLA SCANNER DATALOGIC HERON D130',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	113	,	'D8530',	'PISTOLA SCANNER DATALOGIC D8530',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	114	,	'D9530',	'PISTOLA SCANNER DATALOGIC D9530',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	115	,	'QD2100',	'PISTOLA SCANNER DATALOGIC D2100',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	116	,	'QD2130',	'PISTOLA SCANNER DATALOGIC 2130',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	117	,	'QD2131',	'PISTOLA SCANNER DATALOGIC 2131',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	118	,	'1450GD2',	'PISTOLA SCANNER HONEYWELL 1450G2D',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	119	,	'HS2300',	'SCANNER DA BANCO HS2300 NON ENANCHED',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	120	,	'HS2300-ENANCHED',	'SCANNER DA BANCO HS2300 ENANCHED',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	121	,	'HS3300',	'SCANNER DA BANCO HS3300',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	122	,	'8300',	'SCANNER DA BANCO DATALOGIC 8300',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	123	,	'9800',	'SCANNER DA BANCO DATALOGIC 9800',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	124	,	'8200',	'SCANNER DA BANCO DATALOGIC 8200',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	125	,	'TDK',	'TORRETTA  SCANNER DATALOGIC 9800',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	126	,	'714AB',	'MONITOR SAMSUNG LCD 17"',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	127	,	'6636-AB2',	'MONITOR IBM LCD 15"',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	128	,	'90XX-XX',	'MONITOR IBM LCD 15"',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	129	,	'4820-2WB',	'MONITOR IBM 2WB 12"',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	130	,	'4820-5WB',	'MONITOR IBM 5WB 15"',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	131	,	'4820-51W',	'MONITOR IBM 51W 15"',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	132	,	'4820-5LG',	'MOITOR TOSCHIBA 5LG 15"',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	133	,	'4820-2GB-USB',	'MONITOR IBM 12" INTERFACCIA USB',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	134	,	'4820-4FT',	'MONITOR IBM 12" 4FT',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	135	,	'4820-46D',	'MONITOR IBM 12" 46D',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	136	,	'MQ122E',	'MONITOR FUJITSU 12" MOD. 122E',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	137	,	'KIOSK-NCR',	'KIOSK NCR CLIENTE ESSELUNGA',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	138	,	'4610-KD5 -MEM-LIB',	'BLOCCO MEMORIA 4610-KD5 COMPLETO DI LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	139	,	'4610-KR5-MEM-LIB',	'BLOCCO MEMORIA 4610-KR5 COMLETA DI LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	140	,	'4610-KD5-MEM',	'BLOCCO MEMORIA 4610-KD5 SENZA LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	141	,	'4610-KR5-MEM ',	'BLOCCO MEMORIA 4610-KR5 SENZA LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	142	,	'PROCESSOR-4610-KD3',	'SCHEDA PROCESSOR PER 4610-KD3',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	143	,	'LOGICA-KUBE/PD',	'SCHEDA LOGICA PER  STAMPANTE KUBE/PD215',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	144	,	'TAGLIERINA-KUBE/PD',	'TASGLIERINA PER STAMPANTE KUBE/PD',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	145	,	'TESTINA-PF2I',	'TESTINA TERMICA PER STAMPANTE PF2I',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	146	,	'TESTINA-PM43',	'TESTINA TERMICA PER STAMPANTE INTERMEC PM43',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	147	,	'PM43',	'STAMPANTE INTERMEC PM43 SENZA TESTINA',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	148	,	'PF2I-NEW',	'STAMPANTE INTERMEC MODELLO PF2I MOD NEW',	5,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	149	,	'4610-TM6',	'STAMPANTE IBM TM6',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	150	,	'4610-KD5-MEC',	'STAMPANTE IBM 4610-KD5 SOLO MECCANICA',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	151	,	'4610-KR5-MEC',	'STAMPANTE IBM 4610-KR5 SOLO MECCANICA',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	152	,	'4610-1NF-SLIB',	'STAMPANTE TOSCHIBA 4610-1NF SENZA LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	153	,	'4610-1NR-W',	'STAMPANTE TOSCHIBA 1NR WHITE',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	154	,	'4610-1NR-B',	'STAMPANTE TOSCHIBA 1NR NERA',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	155	,	'TM88',	'STAMPANTE EPSON MODELLO TM88',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	156	,	'FP81',	'STAMPANTE EPSON FP81 COMLETA DI LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	157	,	'FP90-LIB',	'STAMPANTE EPSON MODELLO FP90 COMPLETA DI LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	158	,	'FP90II-LIB',	'STAMPANTE EPSON MODELLO FP90II COMPLETA DI LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	159	,	'NCR-DUAL',	'STAMPANTE NCR DUAL SIDE',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	160	,	'KUBEF-LIB',	'STANPANTE CUSTOM MODELLO KUBEF COMPLETO DI LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	161	,	'PD215-LIB',	'STAMPANTE IBM MODELLO PD215 COMPLETA DI LIBRETTO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	162	,	'XKUBE-LIB',	'STAMPANTE CUSTOM MODELLO XKUBE COMPLETA DI LIBRETTO',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	163	,	'SCX-5637',	'STAMPANTE SAMSUNG MULTIFUNZIONE 5637',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	164	,	'SCX-5635',	'STAMPANTE SAMSUNG MULTIFUNZIONE 5635',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	165	,	'E-STUDIO 425S',	'STAMPANTE TOSHIBA 425',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	166	,	'E-STUDIO 525S',	'STAMPANTE TOSHIBA 525',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	167	,	'6B000000745',	'TONER PER STAMPANTE TOSHIBA 385',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	168	,	'6B000000784',	'TONER PER STAMPANTE TOSHIBA 425',	10,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	169	,	'6B000000619',	'TONER PER STAMPANTE TOSHIBA 525',	5,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	170	,	'6B000000604',	'FOTOCONDUTTORE PER STAMPANTE TOSHIBA 525',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	171	,	'6B000000627',	'FOTOCONDUTTORE PER STAMPANTE TOSHIBA 425',	3,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	172	,	'40X8736',	'ADF PICK ROLLER PER 425/385',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	173	,	'40X8393',	'TRASFERT ROLL PER 425/385',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	174	,	'40X8295',	'MPF PICK ROLLER AND SEPARATOR PER 425/385',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	175	,	'401X0958',	'PICK TIRE PER 425/385',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	176	,	'41X8024',	'FUSER,220 V PER 425/385',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	177	,	'40X8515',	'MS81X FUSER TYPE 28,220-240V PER 525',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	178	,	'40X7593',	'PICK ROLLER PER 525',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	179	,	'40X7600',	'MPF PICK ROLLER PER 525',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	180	,	'40X7713',	'SEPARATION ROLLER PER 525',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	181	,	'40X7601',	'MPF FEED ROLLER FLANGE PER 525',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	182	,	'40X8305',	'CASSETTO E-STUDIO 425S',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	183	,	'40X0976',	'CASSETTO E-STUDIO 525',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	184	,	'3315',	'TASTIERA IBM MODELLO 3315',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	185	,	'6300',	'TASTIERA IBM MODELLO 6300 CON VISORE',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	186	,	'TAST-PS2',	'TASTIER A DA PC PS2',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	187	,	'TAST-USB',	'TASTIERA DA PC USB',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	188	,	'TAST-H&M-PS2',	'TASTIERA BIANCA H&M PS2',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	189	,	'TAST-4820',	'TASTIERINO PER MONITOR 4820 IBM',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	190	,	'LETT-BADGE-51W',	'LERRORE BADBE USB BIANCO PER 51W',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	191	,	'LETT-BADGE-5WB',	'LETTORE BADGE RS2S2 BIANCO PER 5WB/2WB/46D',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	192	,	'LETT-BADGE-5LG',	'LETTORE BADGE USB NERO PER 5LG',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	193	,	'SELESTA-TAU70',	'LETTORE BADGE SELESTA TAU70',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	194	,	'SELESTA-USB-OLD',	'LETTORE BADGE USB PER PC MOD.VECCHIO',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	195	,	'SELESTA-USB-NEW',	'LETTORE BADGE USB PER PC MODELLO NUOVO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	196	,	'VIS-5501',	'VISORE FISCALE IBM MOD 5501 40 CARATTERI MONO FACCIA',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	197	,	'VIS-5502',	'VISORE FISCALE IBM MOD 5502 80 CARATTERI 2 FACCIE',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	198	,	'VIS-5503',	'VISORE FISCALE IBM MOD 5503 20 CARATTERI',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	199	,	'VIS-POLACCO',	'VISORE FISCALE IBM MOD POLACCO 40 CARATTERI MONO FACCIA',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	200	,	'VIS-FUJITSU-CD3220SG',	'VISORE FUJITSU SERIALE MOD CD-3220-SG',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	201	,	'VISORE -FD110-CAB',	'VISORE FISCALE EPSON MOD OLD FD110 CON CAVO ',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	202	,	'VISORE-FD110-CAB-NEW',	'VISORE FISCALE EPSON MOD NEW FD110 CON CAVO ',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	203	,	'VIS-KUBE/PD-2F',	'VISORE FISCALE CUSTOM PER STAMPANTE KUBE 2 FACCIE',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	204	,	'VIS-KUBE/PD-1F',	'VISORE FISCALE CUSTOM PER STAMPANTE KUBE 1 FACCIA',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	205	,	'DGFE-EPSON-OLD',	'SCHEDA DI MEMORIA DGFE PER EPSON',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	206	,	'DGFE-EPSON-NEW',	'SCHEDA DI MEMORIA DGFE PER EPSON FP90III O FP81II',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	207	,	'DGFE-XKUBE',	'SCHEDA DI MEMORIA DGFE PER CUSTOM X KUBE',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	208	,	'DGFE-KUBE',	'SCHEDA DI MEMORIA DGFE PER CUSTOM KUBE',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	209	,	'DGFE-PD215',	'SCHEDA DI MEMORIA DGFE PER PD215',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	210	,	'DGFE-4610 KXX-1GB',	'SCHEDA DI MEMORIA DGFE PER 4610-KXX 1 GB',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	211	,	'HD-IDE -PICCOLO',	'HARD DISK IDE DI PICCOLA TAGLIA ',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	212	,	'HD-IDE-20GB',	'HARD DISK IDE 20 GB',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	213	,	'HD-IDE-40GB',	'HARD DISK IDE 40 GB',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	214	,	'HD-IDE -80GB',	'HARD DISK IDE 80 GB',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	215	,	'HD-IDE-160GB',	'HARD DISK IDE 160GB',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	216	,	'HD-SATA 40GB',	'HARD DISK SATA 40GB',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	217	,	'HD-SATA-80 GB',	'HARD DISK SATA 80 GB',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	218	,	'HD-SATA-80 GB AS',	'HARD DISK 80 GB SATA PER ROLL OUT A&S',	10,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	219	,	'HD-SATA -160GB ',	'HARD DISK SATA 160GB',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	220	,	'HD-SATA-250GB-2,5"',	'HARD DISK SATA 250 GB 2,5"',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	221	,	'HD-SSD-64GB',	'HARD DISK SSD SATA 64 GB',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	222	,	'HD-39M4515',	'HARD DISK PER SERVER TOYS X3400',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	223	,	'MOUSE-PS2',	'MOUSE PC MOD.PS2',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	224	,	'MOUSE-USB',	'MOUSE PC MOD.USB',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	225	,	'BOBINA-336X',	'BOBINA CASSETTO IBM MOD 336X',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	226	,	'CASSETTO-3360',	'CASSETTO DENARO IBM MODELLO 3360',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	227	,	'CASSETTO-3368',	'CASSETTO DENARO IBM MODELLO 3368',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	228	,	'CASSETTO-4781',	'CASSETTO DENARO IBM MODELLO 4781',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	229	,	'CASSETTO-3362',	'CASSETTO DENARO IBM MODELLO FLIP FLOP',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	230	,	'CASSETTO-D5-PLUG',	'CASSETTO DENARO D5 PLUG',	0,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	231	,	'CASSETTO-D5-3',	'CASSETTO DENARO D5 PORTA 3',	2,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	232	,	'CASSETTO-D1-B',	'CASSETTO DENAR0 D1 NERO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	233	,	'CASSETTO-D2-W',	'CASSETTO DENARO D2 NERO',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	234	,	'CASSETTO-CASH',	'CASSETTO DENARO CASH BASIC',	1,	'funzionante'	)	;
INSERT	INTO	prodotto	(id,	codice,	descrizione,	quantita,	stato)	VALUES	(	235	,	'BRIDGE 9800',	'VERIFICATORE BANCONOTE 9800+CAVO USB',	0,	'funzionante'	)	;





INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(1,	1,	1,		2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(2,	2,	2,		6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(3,	3,	2,		-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(4,	4,	1,		6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(5,	5,	2,		-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(6,	6,	2,		6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(7,	7,	3,		-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(8,	8,	1,		3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(9,	9,	3,		5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(10,	10,	2,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(11,	11,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(12,	12,	2,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(13,	13,	2,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(14,	14,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(15,	15,	2,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(16,	16,	2,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(17,	1,	3,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(18,	2,	2,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(19,	3,	1,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(20,	4,	3,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(21,	5,	3,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(22,	6,	3,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(23,	7,	2,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(25,	9,	2,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(26,	10,	1,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(27,	11,	3,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(28,	12,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(29,	13,	3,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(30,	14,	1,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(31,	15,	3,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(32,	1,	2,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(33,	2,	3,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(34,	3,	3,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(35,	4,	2,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(36,	5,	2,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(37,	6,	3,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(38,	7,	1,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(39,	8,	1,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(40,	9,	1,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(41,	10,	2,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(42,	11,	2,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(43,	12,	3,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(44,	13,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(45,	14,	1,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(46,	15,	1,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(47,	1,	1,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(48,	2,	1,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(49,	3,	2,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(50,	4,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(51,	5,	3,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(52,	6,	3,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(53,	7,	2,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(54,	8,	3,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(55,	9,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(56,	10,	2,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(57,	11,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(58,	12,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(59,	13,	3,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(60,	14,	1,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(61,	15,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(62,	1,	3,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(63,	2,	3,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(64,	3,	3,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(65,	4,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(66,	5,	2,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(67,	6,	3,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(68,	7,	2,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(69,	8,	1,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(70,	9,	1,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(71,	10,	1,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(72,	11,	3,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(73,	12,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(74,	13,	2,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(77,	1,	3,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(78,	2,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(79,	3,	3,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(80,	4,	1,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(81,	5,	3,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(82,	6,	2,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(83,	7,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(84,	8,	3,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(85,	9,	3,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(86,	10,	3,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(87,	11,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(89,	13,	3,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(90,	14,	3,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(91,	15,	3,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(92,	1,	1,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(93,	2,	1,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(94,	3,	1,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(96,	5,	3,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(97,	6,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(98,	7,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(99,	8,	2,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(100,	9,	2,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(101,	10,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(102,	11,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(103,	12,	2,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(104,	13,	1,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(105,	14,	1,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(106,	15,	3,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(107,	16,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(108,	1,	3,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(109,	2,	2,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(111,	4,	1,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(112,	5,	2,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(113,	6,	1,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(114,	7,	3,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(115,	8,	2,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(116,	9,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(117,	10,	1,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(118,	11,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(119,	12,	2,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(120,	13,	2,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(121,	14,	2,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(122,	15,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(123,	16,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(124,	1,	2,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(125,	2,	1,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(126,	3,	1,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(127,	4,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(128,	5,	1,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(129,	6,	1,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(130,	7,	3,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(132,	9,	3,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(133,	10,	1,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(134,	11,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(135,	12,	2,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(136,	13,	2,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(137,	14,	3,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(138,	15,	3,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(139,	1,	2,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(141,	3,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(143,	5,	3,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(144,	6,	1,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(145,	7,	3,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(146,	8,	2,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(147,	9,	3,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(148,	10,	1,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(149,	11,	3,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(150,	12,	2,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(151,	13,	3,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(152,	14,	3,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(153,	15,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(154,	1,	2,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(155,	2,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(156,	3,	2,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(157,	4,	2,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(158,	5,	1,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(159,	6,	1,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(160,	7,	3,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(161,	8,	3,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(162,	9,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(163,	10,	2,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(164,	11,	3,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(165,	12,	1,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(166,	13,	3,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(167,	14,	1,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(168,	15,	1,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(169,	1,	2,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(170,	2,	1,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(171,	3,	3,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(172,	4,	1,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(173,	5,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(174,	6,	1,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(175,	7,	2,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(176,	8,	2,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(177,	9,	3,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(178,	10,	1,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(180,	12,	3,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(181,	13,	2,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(182,	14,	3,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(183,	15,	3,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(184,	1,	3,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(186,	3,	1,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(187,	4,	2,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(188,	5,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(189,	6,	1,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(190,	7,	3,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(191,	8,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(192,	9,	2,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(193,	10,	1,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(194,	11,	1,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(195,	12,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(196,	13,	2,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(197,	14,	1,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(198,	15,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(199,	1,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(200,	2,	1,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(201,	3,	1,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(202,	4,	1,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(203,	5,	2,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(204,	6,	2,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(205,	7,	3,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(206,	8,	3,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(207,	9,	1,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(209,	11,	1,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(210,	12,	3,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(211,	13,	1,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(212,	14,	2,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(213,	15,	2,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(214,	16,	3,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(215,	1,	2,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(216,	2,	2,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(217,	3,	2,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(218,	4,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(219,	5,	1,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(220,	6,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(221,	7,	2,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(222,	8,	1,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(223,	9,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(224,	10,	3,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(225,	11,	2,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(227,	13,	1,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(228,	14,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(229,	15,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(230,	16,	3,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(231,	1,	2,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(232,	2,	3,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(233,	3,	1,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(234,	4,	3,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(235,	5,	2,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(236,	6,	2,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(237,	7,	2,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(238,	8,	3,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(239,	9,	2,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(240,	10,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(241,	11,	3,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(242,	12,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(243,	13,	2,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(244,	14,	1,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(245,	15,	3,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(246,	1,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(247,	2,	2,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(248,	3,	1,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(249,	4,	1,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(250,	5,	3,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(251,	6,	1,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(252,	7,	1,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(253,	8,	2,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(254,	9,	1,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(255,	10,	1,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(256,	11,	1,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(257,	12,	2,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(258,	13,	1,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(259,	14,	2,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(260,	15,	1,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(261,	1,	1,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(262,	2,	3,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(263,	3,	1,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(264,	4,	3,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(265,	5,	1,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(266,	6,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(267,	7,	1,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(268,	8,	1,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(269,	9,	1,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(270,	10,	2,	-3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(271,	11,	2,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(272,	12,	1,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(273,	13,	3,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(274,	14,	1,	9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(275,	15,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(276,	1,	2,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(277,	2,	2,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(278,	3,	1,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(279,	4,	2,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(280,	5,	3,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(282,	7,	2,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(283,	8,	1,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(284,	9,	3,	-9	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(285,	10,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(286,	11,	3,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(287,	12,	1,	-1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(288,	13,	2,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(289,	14,	1,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(290,	15,	1,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(291,	1,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(292,	2,	2,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(293,	3,	3,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(294,	4,	2,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(296,	6,	2,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(297,	7,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(298,	8,	2,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(299,	9,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(300,	10,	3,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(301,	11,	3,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(302,	12,	3,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(303,	13,	2,	6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(305,	15,	3,	-6	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(306,	1,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(307,	2,	1,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(308,	3,	3,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(309,	4,	1,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(310,	5,	2,	7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(311,	6,	1,	-10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(312,	7,	2,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(313,	8,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(314,	9,	2,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(315,	10,	2,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(316,	11,	3,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(317,	12,	1,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(318,	13,	2,	8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(319,	14,	1,	-4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(321,	1,	2,	1	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(322,	2,	3,	3	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(323,	3,	1,	-7	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(324,	4,	1,	-9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(325,	5,	3,	8	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(326,	6,	1,	-3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(328,	8,	2,	-3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(329,	9,	1,	-4	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(330,	10,	2,	4	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(332,	12,	2,	-7	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(333,	13,	1,	-6	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(334,	14,	3,	3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(336,	16,	3,	-2	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(337,	1,	1,	-9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(338,	2,	2,	9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(339,	3,	1,	3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(340,	4,	3,	7	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(341,	5,	3,	-5	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(342,	6,	1,	-10	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(343,	7,	3,	-7	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(344,	8,	3,	-8	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(345,	9,	1,	-9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(346,	10,	3,	-9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(347,	11,	2,	-7	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(348,	12,	3,	1	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(349,	13,	3,	2	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(350,	14,	2,	5	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(351,	15,	1,	-10	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(352,	1,	3,	7	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(353,	2,	1,	-4	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(354,	3,	3,	1	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(355,	4,	1,	10	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(356,	5,	1,	-10	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(357,	6,	2,	3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(358,	7,	2,	8	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(359,	8,	2,	-1	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(360,	9,	3,	-2	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(361,	10,	3,	-1	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(362,	11,	3,	-3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(363,	12,	3,	3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(364,	13,	3,	2	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(365,	14,	1,	-9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(366,	15,	2,	9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(367,	1,	3,	-4	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(368,	2,	1,	-6	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(369,	3,	1,	7	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(370,	4,	2,	-2	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(371,	5,	1,	-2	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(372,	6,	3,	-7	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(373,	7,	3,	10	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(374,	8,	3,	10	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(375,	9,	2,	9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(376,	10,	1,	-8	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(377,	11,	2,	-1	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(378,	12,	3,	-4	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(379,	13,	1,	9	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(380,	14,	3,	3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(381,	15,	1,	6	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(382,	1,	1,	8	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(383,	2,	1,	-3	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(384,	3,	1,	5	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(385,	4,	3,	-10	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(386,	5,	3,	10	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(387,	6,	2,	8	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(388,	7,	2,	4	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(389,	8,	3,	-5	,'n'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(390,	9,	2,	2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(391,	10,	1,	-5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(392,	11,	1,	5	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(393,	12,	3,	10	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(394,	13,	2,	-7	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(395,	14,	1,	-2	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(396,	15,	2,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(397,	1,	3,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(398,	2,	2,	4	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(399,	3,	3,	-8	,'y'	);
INSERT	INTO	tracciamento	(id,	id_prodotto,	id_tecnico,	quantita , stato )	VALUES	(400,	4,	2,	-10	,'y'	);
                                                                                                                
DELIMITER $$
DROP TRIGGER IF EXISTS tracciamento_verso_prodotto_ins$$
CREATE TRIGGER `tracciamento_verso_prodotto_ins` AFTER INSERT ON tracciamento FOR EACH ROW
BEGIN
IF  ((Select quantita FROM prodotto where id = NEW.id_prodotto) + (SELECT quantita  FROM tracciamento WHERE id = (SELECT MAX(id) FROM tracciamento ))) >= 0 THEN
  UPDATE prodotto SET quantita = (quantita + (SELECT quantita FROM tracciamento WHERE id =(SELECT MAX(id) FROM tracciamento))) WHERE id = NEW.id_prodotto;
ELSE 
 signal sqlstate '45000' set message_text = 'My Error Message insert';
END IF;
END$$
DELIMITER ;


/*DELIMITER $$
DROP TRIGGER IF EXISTS tracciamento_verso_prodotto_del$$
CREATE TRIGGER `tracciamento_verso_prodotto_del` AFTER DELETE ON tracciamento FOR EACH ROW
BEGIN
IF  ((Select quantita FROM prodotto where id = OLD.id_prodotto) - (SELECT quantita FROM tracciamento WHERE id = OLD.id)) >= 0 THEN
  UPDATE prodotto SET quantita = (quantita - (SELECT quantita FROM tracciamento WHERE id = OLD.id)) WHERE id = OLD.id_prodotto;
ELSE 
 signal sqlstate '45000' set message_text = 'My Error Message delete';
END IF;
END$$
DELIMITER ;*/
